version: 0.2
env:
 parameter-store:
  DOCKER_REGISTRY_USERNAME: /myapp/docker-ceredentilas/username
  DOCKER_REGISTRY_PASSWORD: /myapp/docker-ceredentilas/password
  DOCKER_REGISTRY_URL: /myapp/docker-registry/url
phases:
 Install:
  runtime-versions:
   python: 3.11
  pre_build:
   commands:
   - pip install -r day-14/simple-python-app/requirements.txt
  build:
    commands:
     - cd day-14/simple-python-app
     - echo "Building image"
     - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
     - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/simple-python-flask-app:latest" .
     - docker push "docker.io/priyarrana/simple-python-app:latest"   
  
      # - echo "Hello World"
